### ISSUE TITLE
Add Help Text to Forms

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#10]
Users need to know what to enter into each of the fields on the input forms and so some hover text would be helpful so users know what to enter into each one.  @horsburgh will write text and @jcaraballo17 will implement.

**Comment by horsburgh** [comment]
@mauriel133 - Here is some help text for the elements on the forms. These could replace what is in the text boxes now, or could be added as hover text of some kind.

On the register a site page:

*Site Code*: Enter a brief and unique text string to identify your site (e.g., "Del_Phil").
*Site Name*: Enter a brief but descriptive name for your site (e.g., "Delaware River near Phillipsburg").
*Site Type*: Select the type of site you are deploying (e.g., "Stream").
*Latitude*: Enter the latitude of your site in decimal degrees (e.g., 40.6893).
*Longitude*: Enter the longitude of your site in decimal degrees (e.g., -75.2033).
*Elevation*: Enter the elevation of your site in meters.
*Elevation datum*: Choose the elevation datum for your site's elevation. If you don't know it, choose "MSL".

**Comment by aufdenkampe** [comment]
I have also received the suggestion that we add help text for the Sign Up page, specifically for Organization. 

*Organization*: Begin to enter the common name of your organization to choose from the list. If "No results found", then clear your entry, click on the drop-down-list to select "Add New Organization".

For the "New Organization" pop-up, we need guidance for the Organization Code. Does it need to be unique? If so, is there a system we can recommend? The idea I received was to link to six-character Federal School Code (also known as a Title IV Institution Code), but those won't serve many users, and are not understandable on their own.

**Comment by horsburgh** [comment]
Implemented on production. Closing.
