### ISSUE TITLE
Add Bosch as a Sensor Manufacturer

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#108]
Bosch Sensortec
https://www.bosch-sensortec.com/bst/home/home_overview

Bosch Sensortec GmbH
Gerhard-Kindler-Straße 9
72770 Reutlingen / Kusterdingen
GERMANY

Phone: +49 7121 35 35900
Fax: +49 7121 35 35909

**Comment by fryarludwig** [comment]
Done
