### ISSUE TITLE
Change manufacturer of BMP280 and BME280 to Bosch

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#109]
Currently listed as Seeed Studio, which distributes the sensor on a chip

**Comment by SRGDamia1** [comment]
Does installing the sensor on a chip with resistors and easy communication attachments make it a new sensor?  That is what Seeed (and a variety of others) do.

**Comment by fryarludwig** [comment]
I've updated the BME280, but I don't see a BMP model in the database. Do you know what attributes it should have?

I think the sensor model is more important than the board and support components. All the board is meant to do is get you the results from the sensor. Plus it'd take a ton of work to maintain a list of the 3rd party manufacturers and their various boards that all use the same dozen sensors.

**Comment by SRGDamia1** [comment]
Oh, sorry, no, the BMP isn't on the list.  Don't worry about it.
