### ISSUE TITLE
Delete Site button URL not working for non-owned sites

### ISSUE THREAD

**Issue by fryarludwig** [ODM2/ODM2WebSDL#117]
The URL for delete sites does not work. Example:

http://data.envirodiy.org/sites/delete/qwerqwer/

**Comment by fryarludwig** [comment]
Correction: The delete site URL fails when a super users tries to delete a site owned by another user.

**Comment by aufdenkampe** [comment]
This is fixed, right?

**Comment by fryarludwig** [comment]
Yes, this fixed and on production. I'll close this issue.
