### ISSUE TITLE
Unable to add data to recently created sites

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#129]
When I try to append the data I'm getting a 500 response "Server Error (500)".

Oddly, after the first time I try to append the same data point, I get a 400 error with the message ""detail":"xxxxxx value not saved duplicate key value violates unique constraint"

I *am* able to append data to older site (>1 week or so).

**Comment by SRGDamia1** [comment]
See #130, but the data definitely *is* being appended, even though a server error is returned.

**Comment by jcaraballo17** [comment]
Pushed a hot-fix for this issue. It should be working fine now.

**Comment by SRGDamia1** [comment]
I started getting 201's instead of 400's, so it seems to be working.
