### ISSUE TITLE
Add ability to record "recieved time"

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#13]
Do we want to record the time a string was received by the server as a very rough verification of the logger clock?

**Comment by horsburgh** [comment]
Is there a particular use case for this that you had in mind? There is nowhere in the underlying ODM2 database to store this information.

**Comment by SRGDamia1** [comment]
We've been keeping the server time in our current configuration.  I think right now Shannon is using it for convenience for plotting, but I don't know if it's really needed for anything else.

**Comment by SRGDamia1** [comment]
I don't think this is important enough to bother with.
