### ISSUE TITLE
Add ability to recieve data from multiple sampling features from a single logger.

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#14]
One of our user groups is already planning to deploy sensors with a ultrasonic water depth sensor in the stream and then a soil moisture sensor on the bank next to it.  Can (or should) we implement these as separate sampling features.

**Comment by horsburgh** [comment]
I would consider these to be the same site sampling feature. You select the sampled medium when you map a sensor/variable to the site/logger, so you can have measurements from water and soil coming from the same logger via a single POST request.

Another option is to register two sites with the website - one for the stream and one for the soil. But, then the logger would have to send POST requests to the website for two different sites. The website will allow this already, but the logger would have to be programmed to send POST requests for two different sites.

**Comment by SRGDamia1** [comment]
Hm.  Ok, I think the first option probably would work for the Sustainable Business Network group that is planning to use the ultrasonic/soil moisture pair.  Should we include an ability to put in some sort of location offset?

We've also done things in-house with using long cables to attach transducers in several wells to the same logger.  But I don't think we have any other groups that are immediately planning to set anything else up like that.

**Comment by horsburgh** [comment]
@SRGDamia1 - I'm closing this one because it is covered by existing functionality. If we need a separate issue to deal with offsets, please add a separate issue.
