### ISSUE TITLE
Create "Add New Equipment Make-Model" web form for super users

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2WebSDL#144]
Creating this new issue to track development of this feature, described in #94.

**Comment by horsburgh** [comment]
@aufdenkampe - Can you just elaborate on what you want here in this issue. That way people don't have to wade through all of the other stuff in the other issue to find what you mean.

**Comment by aufdenkampe** [comment]
Thanks for the nudge. My original title wasn't very descriptive! I just edited it for clarity.

This issue is to create the "super user Django form for you to add sensors to the list. It will be included in release 0.5.0. My preference would be for you to use this form to add new sensors", as described by @horsburgh in this comment: https://github.com/ODM2/ODM2WebSDL/issues/94#issuecomment-360637852.

@jcaraballo17 and @Maurier, please use this issue to share and discuss any design ideas that you might have.

**Comment by horsburgh** [comment]
@aufdenkampe - if this is a duplicate of #71 can you please close this issue?

**Comment by aufdenkampe** [comment]
Yes! Thanks for noticing that I had mistakenly created a duplicate!
