### ISSUE TITLE
Add ability to delete a registered site

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#15]
Need the capability to delete a site once it has been registered. This would have the action of deleting all traces of this site and any associated data from the underlying database. There should be a warning message the pops up telling the user that deleting a site is permanent and that all associated data will also be deleted. They must confirm to delete the site.

**Comment by SRGDamia1** [comment]
This is complete, right?

**Comment by jcaraballo17** [comment]
@SRGDamia1 yes.
