### ISSUE TITLE
Add a page to display current time for clock sync

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#16]
When hooked up to the WiFiBee, the Mayfly can only connect to a single IP address.  It would be great if somewhere on your IP you could set up a very short page only displaying the current US NTP unix timestamp to help sync the clocks regularly.  Something analogous to http://time.sodaq.net/.

The RTC in the Mayfly is supposed to be very good, but it never hurts.

**Comment by horsburgh** [comment]
@SRGDamia1 - is this something we could implement on the REST API so that you could send an HTTP GET request from the Mayfly and get back the unix timestamp?

**Comment by SRGDamia1** [comment]
An HTTP GET response would be awesome.  It just has to be available at the same IP address that the POST request must go to.

**Comment by SRGDamia1** [comment]
I have figured out how to easily get this data from NIST.  This is no longer necessary.
