### ISSUE TITLE
Add ability to download data file as CSV

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#18]
Need to add a button to each time series on the site details page that enabled download of the time series as a CSV file. The file should be simple - use the same file template used by ODMTools Python for time series export. @sreeder can get you the format.

**Comment by SRGDamia1** [comment]
This is a feature that is really necessary as soon as possible.  Please put it in the next milestone!

**Comment by horsburgh** [comment]
@SRGDamia1 - this will come as soon as we have the Time Series Analyst set up.  We are oh-so-close to having a working instance of WOFPy on the production database.

**Comment by horsburgh** [comment]
Implemented and pushed to production. Download button is at the top of the sparkine box for each variable. Closing.

**Comment by aufdenkampe** [comment]
Awesome! Thanks for this good work!
