### ISSUE TITLE
Have correct time axis in sparkline plots

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#20]
The spacing on the spark-line plots does not match up with the actual timing of samples.  It's particularly evident in http://data.envirodiy.org/sites/28/ where I've turned the logger on and off several times leaving multiple gaps, but there are no gaps visible on the plots.

**Comment by SRGDamia1** [comment]
This is a feature that is really necessary as soon as possible. Please put it in the next milestone!

**Comment by horsburgh** [comment]
@Maurier - I see you've been assigned by @jcaraballo17 . Can we try setting the sparkline plots to show the last 72 hour period rather than the last x number of data values. If there are gaps in data for the 72 hour period, then those gaps should show up in the sparklines.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing

**Comment by SRGDamia1** [comment]
Is there a way to view this on the sandbox server?  All of the data in the sandbox is old, so all plots just show up as blanks for me.

**Comment by horsburgh** [comment]
@SRGDamia1 - the whole project is live on the sandbox server, but it has its own database because we don't want our testing to affect the production database. But, you should be able to stream data to the sandbox just like the production server and then we could see these changes.

**Comment by horsburgh** [comment]
The time axis showing 72 hours has been implemented on production. Discussion about breaks in the plot is in issue #45  so I'm going to close this issue.
