### ISSUE TITLE
Make the time the last data point was recieved prominanty visible.

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#22]
For easily checking the status of each station, we need to know quickly the last time a data point was received.  Currently the only way to find the time is to go to each site, then click on the tabular data view, then scroll to the bottom.  I would like to see the time of the most recent point above the plots for each station.  I would also prefer to see the time of the most recent point at each station on the "My Sites" pane in place of the "Registration Date".

**Comment by horsburgh** [comment]
@SRGDamia1 - we need to keep the "Deployment date" in the informational table on the site details page. But, yes, we need to add the most recent date on which data were received from the site in the "Recent Measurements" section.

**Comment by SRGDamia1** [comment]
Can you replace the registration date with the most recent date/time in the site pane?
![capture](https://cloud.githubusercontent.com/assets/5374350/22841884/44eb1528-efa1-11e6-9bea-6fd0a14dedba.PNG)

**Comment by horsburgh** [comment]
This is done on production. The last date update on my site was incorrect because I failed to update the time on my Mayfly board before I started logging data. Closing.

**Comment by SRGDamia1** [comment]
Just FYI, I've made a nice little python script (and compiled executable of it) to update the clock:  https://github.com/EnviroDIY/Sodaq_DS3231/tree/c61d88dec9f7f88859f0dffe3ec873886a50301e/examples/PCsync

**Comment by horsburgh** [comment]
@SRGDamia1 - thanks. I knew you had done this, but I was too lazy to track it down.
