### ISSUE TITLE
Make satellite view the default in a single site's page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#25]
I just think it looks prettier.  When zoomed in to a single site, the map view has very little detail on it so the satellite view seems nicer.

**Comment by jcaraballo17** [comment]
Should this be just in the site page? What type of maps do we want on the "My Sites" and "Browse Sites" pages?

**Comment by horsburgh** [comment]
Yes - just on the individual site page. The other pages are fine as they are.

**Comment by horsburgh** [comment]
This is done on production. Closing.
