### ISSUE TITLE
Remove the "view site" link from site box and make site code a hyperlink

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#27]
I keep clicking on the name anyway.  Removing the extra block on the bottom should also make it more friendly on small screens.  (Sorry for the really ugly art skills..)
![capture](https://cloud.githubusercontent.com/assets/5374350/22839815/fdd1ce96-ef98-11e6-84e1-7fe5c4d24cec.PNG)

**Comment by SRGDamia1** [comment]
Sorry, this is on the "My Sites" pane.

**Comment by horsburgh** [comment]
This is done on production. Closing.
