### ISSUE TITLE
Remove redundant site code in under Sampling Feature in My Sites pane

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#29]
Under the sampling feature, the site code is concatenated to the name.  Since the box title is already the site code, this is redundant.
![capture](https://cloud.githubusercontent.com/assets/5374350/22841956/88b2172a-efa1-11e6-9ff8-a2a265bcb4c3.PNG)

**Comment by jcaraballo17** [comment]
In this case, I'm making the Sampling Feature Name required to make sure there's always something to show there.

**Comment by horsburgh** [comment]
This is done on production. Closing.
