### ISSUE TITLE
Allow users to include sensor serial numbers

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#32]
Was there a reason this was not included?  @aufdenkampe  ?  I don't remember if we deemed it excessive for citizen scientists.  I think it would actually be more educational for them to realize that things like the differences between unique sensors can make a difference in the data quality.  Of course, it could also lead to problems if people decide to change out their sensors without reprogramming their board with the new UUID's.

**Comment by horsburgh** [comment]
Given the complexity of what will have to be done to implement this (not only in explaining to users, but on the back end of the site as well), I recommend not doing this. We are building a citizen science data contribution site - not a full blown scientific data management system. Need to keep the users and use cases at the front.

**Comment by SRGDamia1** [comment]
Closed in favor of #134.
