### ISSUE TITLE
Post fails if sent while site view is refreshed

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#35]
If I refresh the page to view data from a site (http://data.envirodiy.org/sites/28/) at the same time as I send a post request, one or both of the refresh and the post seems to fail.

**Comment by horsburgh** [comment]
I believe that this is part of the scalability investigation we are doing right now. We are setting up a deployment environment in Linux with the goal of moving from our current Windows hosting environment to a more native Linux environment for Django. 

The Windows deployment is having trouble walking and chewing gum at the same time...

**Comment by SRGDamia1** [comment]
Oh Windows..
