### ISSUE TITLE
Add data sharing agreement to the sign up page

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#37]
Need to add a check box at the bottom of the sign up page with the following text:

* [ ] I agree that all of the data I post to this site will be made public according to the Creative Commons Attribution Share Alike License (CC-By-SA).

You should also add the appropriate creative commons license badge/icon below the text:

https://licensebuttons.net/l/by-sa/4.0/88x31.png 

Details of the license at: https://creativecommons.org/licenses/by-sa/4.0/ 

This URL should be linked in some way to the text and/or icon.

If a user does not check this box, do not create an account for them, pop up a message that says:

"To post data to this site, you must agree to the open data license."

**Comment by horsburgh** [comment]
Moved this to the next milestone since it was the only one left on 0.1.0.

**Comment by SRGDamia1** [comment]
This is complete, right?
