### ISSUE TITLE
Expand Sensor List

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#38]
The list of sensors available for registration needs to be updated based on the list in the following Goggle Doc.

https://docs.google.com/spreadsheets/d/1x87AHmmCWmsgMVpbeEhw9iZm5iHPiUoJPuaUpzHsxW0/edit#gid=630637297

**Comment by jcaraballo17** [comment]
List updated!

**Comment by horsburgh** [comment]
@aufdenkampe - can you have a look at the updated list and if it looks good can you close this issue?

**Comment by horsburgh** [comment]
Haven't heard anything, so I'm going to assume this is done and am closing. We can open a new issued if the list is not as required.

**Comment by aufdenkampe** [comment]
The sensor list was updated on February 22 and is great for now!

Sent from my iPhone

On Mar 10, 2017, at 5:22 PM, Jeff Horsburgh <notifications@github.com<mailto:notifications@github.com>> wrote:


Haven't heard anything, so I'm going to assume this is done and am closing. We can open a new issued if the list is not as required.

-
