### ISSUE TITLE
Firefox Security Warning

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#42]
I'm getting a security warning in Firefox when logging on to the portal:
![capture](https://cloud.githubusercontent.com/assets/5374350/24157608/38c6ff2a-0e30-11e7-88c3-8f16b46f06b9.JPG)

**Comment by horsburgh** [comment]
@SRGDamia1 - this is a "feature" of Firefox that will likely show up for any login on any site that does not use HTTPS.

https://support.mozilla.org/t5/Protect-your-privacy/Insecure-password-warning-in-Firefox/ta-p/27861

**Comment by SRGDamia1** [comment]
Should we be using HTTPS?
