### ISSUE TITLE
Add horizontal axis ticks to the sparkline plots

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#45]
Going along with #20, add some tick marks to the horizontal axis with standardized (6 or 12 hour) spacing.

**Comment by SRGDamia1** [comment]
I think that is probably ok, then, as long as the amount of time shown on the spark lines is always consistent and gaps appear where there are real gaps in the data.

**Comment by horsburgh** [comment]
@SRGDamia1 - agreed. We can work on those issues.

**Comment by horsburgh** [comment]
@Maurier - this one will be resolved when you set the time window for the sparklines to 72 hours and show gaps if they occur.  For now, let's not add axis ticks to the sparklines.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing.

**Comment by horsburgh** [comment]
@Maurier - it looks to me like you have now made the x-axis of the sparklines a time scale of 72 hours. Did you implement breaking the sparkline if there are time gaps in the data? If so, what rules did you use to determine where to break the line?

@SRGDamia1 - given that users can POST data to the database at whatever time frequency they like, including a time frequency that may vary, how should we identify gaps where the line should actually break?

**Comment by Maurier** [comment]
@horsburgh I did not implement breaking the sparkline precisely because we have no definition for gaps in the data. 

Let me know what what rules we agree on and I'll add them if needed.

**Comment by horsburgh** [comment]
@SRGDamia1 and @aufdenkampe - I am leaning toward back-burnering this one. Given the diversity of what we may receive in terms of data posted from various devices, I'm not sure how to define a set of rules for how/when to break the lines in the sparkline plots. We could set some rules like if the distance between two data points is greater than some arbitrary time period we create a break. Or, we could try to be more sophisticated and try to infer the intended spacing from the data and then break it if there is a gap longer than a certain number of data points. However, this would complicate things and slow down the loading of the page.

Do you guys have ideas about the rules we should use for identifying gaps were we should break the sparklines?

**Comment by SRGDamia1** [comment]
I'd prefer to infer the spacing, but not at the expense of a large slow-down.  Other than that, I would use a gap of ~6 hours.

**Comment by horsburgh** [comment]
@Maurier - can you modify the sparkline plots to break the lines if there is a gap longer than 6 hours?

**Comment by Maurier** [comment]
Yes, I'll take care of that.

**Comment by aufdenkampe** [comment]
That sounds like a reasonable approach to me. Thanks.

**Comment by fryarludwig** [comment]
To summarize, we've agreed to create break the lines in sparkline plots when there is a coverage gap of more than 6 hours. Sparkline plots on Device Details pages will cover the latest 72 hours of data values.
