### ISSUE TITLE
Timestamp when viewing tabular data is incorrect

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#46]
All the data from within an hour is displayed as 5-minutes after the hour, and after the wrong hour at that.  Hopefully this is only a display issue.  The most recent time in the screen capture should be 11:50 EST.

![capture](https://cloud.githubusercontent.com/assets/5374350/26319542/713accea-3eed-11e7-9176-f5cdc7ae463f.JPG)

**Comment by Elijahwalkerwest** [comment]
Pushed changes to sandbox, now ready for testing.

**Comment by horsburgh** [comment]
Just posted several data points to a new site on the production server. All dates/times appeared correct. Closing.
