### ISSUE TITLE
When initially accessing web page, immediately zoom in on map based on browser location

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#48]
Instead of opening to a map of the entire US, immediately zoom to about level 15 based on the location information given by the browser, if available.

**Comment by horsburgh** [comment]
@SRGDamia1 - I'm assuming you mean the "Browse Sites" page here?  The "My Sites" page should zoom to the extent of the user's sites. An individual site details page should zoom to the location of that site.

**Comment by SRGDamia1** [comment]
Yes, on the "Browse Sites" page.

**Comment by Elijahwalkerwest** [comment]
Pushed to sandbox, plays nice with map zoom based on browser session also.

**Comment by darscott** [comment]
Works on 1st entry to "Browse Sites". However, the zoom extent that was last viewed seems to be remembered and so any re-entry to "Browse Sites" shows the previous zoom extent instead of a zoom to browsers location. I would prefer that any time you hit the "Browse Sites" link, the view returns to the  level 15 based on the location information given by the browser.

**Comment by Elijahwalkerwest** [comment]
This behavior is directly at odds with issue 49. Right now both are satisfied. On first visit to the page browser location is used to determine map location and zoom, then your current zoom and latitude long is remembered for that session. 

Can you explicate on how exactly you'd like this to behave?

**Comment by horsburgh** [comment]
@darscott - @Elijahwalkerwest noticed that the request you made above does conflict with what @SRGDamia1 requested in #49. Right now, the behavior is that when you first visit the "Browse Sites" page, it is automatically zoomed to your location (as this issue requested). Then, the site remembers your zoom level during the current session and takes you back to the remembered zoom level each time you go back (as issue #49 requested). 

We can modify this if you want, just let us know what you and @SRGDamia1 decide you would like to do.

**Comment by horsburgh** [comment]
The original issue has been implemented on production. Works in concert with the retaining of zoom level requested in #49. Closing.
