### ISSUE TITLE
After leaving a map to look at the data from a site, return to prior zoom level when returning to map

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#49]
Maintain the map zoom level while on a single browsing session, especially when hitting the back button after viewing a site.

**Comment by horsburgh** [comment]
@SRGDamia1 - I'm assuming you mean the map on the "Browse Sites" page here.

**Comment by SRGDamia1** [comment]
Actually, for either the browse sites *or* my sites in this case.

**Comment by Elijahwalkerwest** [comment]
Pushed to sandbox server and ready for testing.  I did some testing myself and it looks good, let me know if it functions like you want. Right now this is implemented for both my sites and browse sites and is linked to browser session. Though My Sites will still have its zoom and lat lng set to the site marker upon first visiting that page.

**Comment by darscott** [comment]
Tested on three map locations/sites...works as expected

**Comment by horsburgh** [comment]
Deployed on production. Closing.
