### ISSUE TITLE
Add the ability to log-in as a "local administrator"

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#50]
I am frequently creating sites for other users.  It would be nice for me (and others) to more easily be able to administrate other sites rather than creating multiple log-ins and regularly logging in and out as the other users.

**Comment by horsburgh** [comment]
@SRGDamia1 - would a super user account work for you that gives you access to edit other people's sites?  @jcaraballo17 - is this possible in the current system?

**Comment by SRGDamia1** [comment]
I think that would work.

**Comment by horsburgh** [comment]
@jcaraballo17 - I see you assigned yourself. Is it possible to get @SRGDamia1 set up with an account that she can use to oversee the registrations made by others?

**Comment by horsburgh** [comment]
@SRGDamia1 - our current plan for this is to create an administrative account for you. You would be able to see and edit any existing site registrations in the system. You could also register sites for other people. Our plan is that if an administrator is registering a site, they would get drop down of users (including themselves) where they would select the user for which they are registering the site. Does this meet your needs?

**Comment by SRGDamia1** [comment]
That sounds great.

**Comment by jcaraballo17** [comment]
Realized this can't be tested by other people if there are no other administrators. Added @horsburgh and @SRGDamia1 as administrators in the sandbox.

**Comment by SRGDamia1** [comment]
Am I an admin under my already-existing account under "SGDamiano1" or did you make a new user for me.  If so, please email me the new username and pw.

**Comment by jcaraballo17** [comment]
Yes, I changed your existing account to be an administrator.

**Comment by SRGDamia1** [comment]
Thanks.  Now how do I create sites for others or edit other people's sites?

**Comment by jcaraballo17** [comment]
When you're an administrator, the Register Site form has a new field called Deployed By in which you choose for whom you're registering the site. Also, when you go on a site detail page, the Edit and Delete buttons are available to you. 
Surely we're gonna need to change some things, but I'd like some feedback on that first. If you have any ideas on how to make it better or if you think it needs to be different, please let me know.

**Comment by SRGDamia1** [comment]
I am not seeing the extra fields right now.  Could I have multiple users and be using the wrong one?

**Comment by jcaraballo17** [comment]
Yes, I had given permissions to another user with your name, but it's fixed now. Now all of them are admins.

**Comment by SRGDamia1** [comment]
Ok, I see it now.  Can I create a user when I'm creating a site or just select from the already registered users?

**Comment by horsburgh** [comment]
@SRGDamia1 - The other user will have to exist first before you can create a site on their behalf.  You could, of course, go to the user registration page, register the user, and then that user will show up in the list.

**Comment by SRGDamia1** [comment]
That is what I've been doing up until now.  Thanks.

**Comment by horsburgh** [comment]
This has been deployed to production. Closing.
