### ISSUE TITLE
Automatically merge turbidity data from two ranges

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#51]
The Campbell OBS3's output turbidity in two ranges, which seems to be quite confusing to users.  When plotting long-term turbidity, it would be helpful to users to create a "merged" plot of the turbidity.  (That is, the low range value when the sensor is inside the limits of the low range, and the high range otherwise.)

**Comment by horsburgh** [comment]
@SRGDamia1 - given that this is specific to one sensor/output variable, would it make more sense to handle this in the datalogger program so that the website never knows about this complexity?  For example, modify the code on the datalogger to just submit the correct turbidity value to the website after making the decision on the logger to submit the high or low range value.

**Comment by SRGDamia1** [comment]
We definitely want the datalogger to output (and the portal to receive and display) both ranges of turbidity.  I would prefer the merging not to be done on the processor because it's more of analysis and correction, but I am thinking about how I can do it with my current logger program structure.

**Comment by horsburgh** [comment]
@SRGDamia1 - If this rises up to a higher level of importance, we can consider it further. But, if you want the logger to output and for the data.envirodiy.org website to receive and display both turbidity time series, then they are effectively two time series.  Data post processing of this type is a bit more advanced than what we had planned.

**Comment by aufdenkampe** [comment]
I agree with Jeff on this. Such a feature belongs in a different web application. WebSDL / Data.EnviroDIY should focus on helping users register their stations and then stream raw data.

**Comment by horsburgh** [comment]
@aufdenkampe - if you guys are in agreement on this, I'll let you close this issue.

**Comment by horsburgh** [comment]
Based on discussion, I'm closing this issue.
