### ISSUE TITLE
Development Setup

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2WebSDL#55]
How can I set up a dev environment for this?

**Comment by horsburgh** [comment]
@denvaar - did anyone ever respond to you about this?

**Comment by denvaar** [comment]
@horsburgh No, I would like to set it up, but I am not sure what environment variables I need and database details, etc.

**Comment by horsburgh** [comment]
@jcaraballo17 - can you help @denvaar with this?  Is it documented anywhere?

@Elijahwalkerwest - is this something you could help @denvaar with? I'm not sure if Juan is settled back in the DR yet.

**Comment by jcaraballo17** [comment]
@denvaar There's a requirements.txt in the project. I just updated to match my own development environment.

**Comment by jcaraballo17** [comment]
Also realized the settings template wasn't in the repository, so added one. Just fill out the empty strings in settings_template.json with your own development database and rename it to settings.json when you're done.

**Comment by denvaar** [comment]
Thanks @jcaraballo17 🐎

**Comment by horsburgh** [comment]
Assuming this is resolved. Closing.
