### ISSUE TITLE
Profile page - Save Changes redirects away to home page

### ISSUE THREAD

**Issue by Maurier** [ODM2/ODM2WebSDL#60]

**Comment by horsburgh** [comment]
@Maurier - what is the desired functionality? Stay on the profile page?

**Comment by Maurier** [comment]
@horsburgh, after saving the changes it should refresh the page to view mode.

**Comment by horsburgh** [comment]
OK. Agreed.

**Comment by horsburgh** [comment]
This is fixed on the sandbox. Can close when it has been deployed to production.
