### ISSUE TITLE
Edit Site Page: Change "Register Site" button to "Save Edits"

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#61]
When editing a site, I have already registered that site. So, the button at the bottom of the form should be changed from "Register Site" to "Save Edits".

**Comment by horsburgh** [comment]
This is fixed on the sandbox. Can be closed when pushed to production.

**Comment by aufdenkampe** [comment]
I'm happy to close now, as it will be resolved when pushed to production.
