### ISSUE TITLE
Modify Sparkline Plots to Show Data Even if Stale

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#62]
Right now, if the site has not collected any data for the past 72 hours, all of the sparkline plots are blank and a message is displayed on each sparkline saying that no data has been collected in the last 72 hours. I think this could be mistaken by users who might think that no data is available for the site at all.  So, I suggest the following:

* [x] Always display the most recent 72 hours of available data in the sparkline plot so there is always data in the plot (unless no data exist at all). "Most recent" = the 72 hour period prior to the last observation in the database.
* [x] Color the panel containing the sparkline light green if the data are within 72 hours of the current system time. This indicates that data collection for that variable is active.
* [x] Color the panel containing the sparkline light red if the data are older than 72 hours prior to the current system time. This indicates that data collection for that variable is not active.
* [x] Change the message at the top of the sparklines to read "Only the most recent 72 hours of available data are shown on the sparkline plots."
* [x] Add a timestamp to each sparkline panel formatted as "Date of last observation: <Timestamp>" where <timestamp> is the date of the the most recent observation recorded in the database.

**Comment by Maurier** [comment]
Here how it looks like after implementing the items above. Let me know if this works.

![image](https://user-images.githubusercontent.com/2448568/29105429-ad89e278-7c8a-11e7-8a94-b3e6d24cfe96.png)

**Comment by horsburgh** [comment]
@Maurier - these look great. Given that we would now have the red and green shading, I suggest getting rid of the light grey shading under/over the plot lines. Is that possible?

**Comment by Maurier** [comment]
Yes. Also, could you specify a message to show when there is no data available to display?

**Comment by horsburgh** [comment]
I think the message "No data exist for this variable." would work.

**Comment by Maurier** [comment]
Done. Updated screenshots above.

**Comment by horsburgh** [comment]
OK one last thing here. Add the following text to the blue label where it says only the most recent 72 hours of available data are shown. Leave the existing text, just add this text on.

"Plots highlighted in red have no data available for the past 72 hours. Plots highlighted in green have been active within the last 72 hours."

**Comment by horsburgh** [comment]
I'm not sure this one is working quite right. See this site:

http://envirodiysandbox.usu.edu/sites/USU-Logan-Temp/

There's data for temperature. I can view it in the table. But, the plot doesn't show any data.

**Comment by horsburgh** [comment]
@Maurier - I think this one's yours right?

**Comment by Maurier** [comment]
Yes, I will address it this morning.

**Comment by Maurier** [comment]
This should be working fine now: http://envirodiysandbox.usu.edu/sites/USU-Logan-Temp/

**Comment by aufdenkampe** [comment]
It's working for me.
