### ISSUE TITLE
Create tagged Releases, with version numbers that match Milestones.

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2WebSDL#63]
These official releases are best created as soon as the release goes to "Production"

**Comment by horsburgh** [comment]
We will start this with Version 0.4.0 to match the next milestone.

**Comment by horsburgh** [comment]
I'm assuming we can issue a release of the 0.4.0 milestone when it is complete. @jcaraballo17 - what will be included in the release? This issue can be closed as soon as release 0.4.0 for this milestone is made in GitHub.

**Comment by aufdenkampe** [comment]
@fryarludwig, @Maurier, @Elijahwalkerwest and @jcaraballo17, @sreeder
Let's make this happen by the end of the week, even if the release notes need to get completed later.
