### ISSUE TITLE
Add last time received to the individual site page

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#67]
Currently you can see the time the last data point was received on the "my sites" page, but not on the page of an individual site.  This means if you're browsing other people's sites, to find out the last time for the site you have to click on the tabular data for one of the variables and scroll down to the most recent measurement.  It should be much easier to see.

![capture](https://user-images.githubusercontent.com/5374350/29195079-a6cdb150-7dfa-11e7-8f37-8898a4c9bec7.JPG)

It would be great to see that same value on the pop-up for each site:
![capture2](https://user-images.githubusercontent.com/5374350/29195110-ce577288-7dfa-11e7-82fe-088aacadabdc.JPG)

**Comment by SRGDamia1** [comment]
Oops, sorry, I guess this is partly within #66 , but I would like the time to be included along with the date.

**Comment by horsburgh** [comment]
@SRGDamia1 - see the latest screen shots from @Maurier in #66. The most recent date/time for each variable will be shown with the sparkline for that variable. So, that should cover that part of this issue.

@Maurier and @jcaraballo17 - would it be easy to add the date/time of the last data point received in the site information pop-up in Google Maps on the My Sites and Browse Sites pages? See Sara's second screen shot above.

**Comment by SRGDamia1** [comment]
@horsburgh - I'm sorry, I created this issue before seeing #66.  The most recent screenshots there fix the first part.

Sorry for the hideous screen shots!

**Comment by horsburgh** [comment]
@Maurier and @jcaraballo17 - testing on the sandbox, I see the date of the latest measurement from each site on the "My Sites" page and next to the sparkline plots on the site details page. Those look good.  The second part of this issue was to add the date of last measurement to the pop ups in the Google maps. I don't see it there on the sandbox. Is this something that can be done quickly?

**Comment by Maurier** [comment]
Latest Measurement has been added to Google Maps markers and other places on the site.
