### ISSUE TITLE
Add the ability to "like" or follow another person's site

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#69]
Have a way to follow any other site so that it appears either below "my sites" or on a separate page of "my favorites" or something of the sort.  Also include these "followed" sites  in the status page.  This allows users to monitor a site that they have not personally set up.

**Comment by horsburgh** [comment]
This could be done by adding a "Follow this Site" button to the site details page for each site. This button would show up when viewing the site details page for any site that is now owned by the viewing user. "Followed" sites would then be added to the user's list of "My Sites". There should be some visual distinction between sites owned/created by the user and sites that have been followed by the user. They might even be separated into two separate sections on the page. They may also be shown as two different marker types on the Google Map on the "My Sites" page.

**Comment by fryarludwig** [comment]
This is deployed to production.
