### ISSUE TITLE
Add ability to export Arduino code for a registered site

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#7]
Once a user has registered a site and added sensors to it, add a button to the site details/registration page that exports a code block with the following:

* SamplingFeatureUUID
* Time zone/UTCOffset Information
* SecurityToken
* ResultUUIDs for any attached sensors

This would enable us to use standardized code for the rest of the Arduino code, but the users can paste this code into the standard code. Still need to define exact content and format of the code that is exported.

**Comment by fryarludwig** [comment]
We'll be basing the snippet generator off this .ino file:
https://github.com/EnviroDIY/ModularSensors/blob/master/examples/logging_to_EnviroDIY/logging_to_EnviroDIY.ino

**Comment by SRGDamia1** [comment]
@fryarludwig, please let me know if there's anything in that .ino that you don't understand!

**Comment by fryarludwig** [comment]
As of my latest push, the devices page creates code that has each of the device's and sensors' UUIDs (see screenshot below). This is far from a full .ino file generator, but there are enough challenges (pins used, calibration values, header includes, and sensor initialization) that reliably generating full files would optimistically take about a week. 

To generate the full .ino file, we would need to gather all of the sensor class names and constructors from the sensor repository, know which sensors require which pins and which calibration values (we could leave these blank for the user to fill in), and assume serial port details. We would also need a way to handle new sensors that are added after the release of this tool. There would still be a lot of values for the user to fill in, but it may save enough time to be useful. What's the group consensus on this? (We could also wait on the full .ino file generator for a later release, if there are higher priorities right now)

![image](https://cloud.githubusercontent.com/assets/8953221/24583797/169305a6-1714-11e7-94a6-f2a3265a7245.png)

**Comment by horsburgh** [comment]
@fryarludwig - rather than displaying the code on the page, let's add a button that opens a modal window.

@SRGDamia1 and @aufdenkampe - I think we probably need some feedback from you guys on this.

**Comment by aufdenkampe** [comment]
@fryarludwig, thanks for all this hard work! What you just showed looks like a great help, and I'm leaning toward releasing the next version based on just generating the code snippets with the UUIDs and leaving the full .ino generation for a later release, because, as you point out, @SRGDamia1  and I will need to do some work to provide additional information about the pin configurations for each sensor, etc.

I also agree that there may be some higher priority issues to work on, which you could do in parallel to the our work.

Let's meet this week to discuss next steps.
