### ISSUE TITLE
Make Anthony a super user

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#72]
@aufdenkampe

**Comment by horsburgh** [comment]
Moving this one to the next milestone as I want to close 0.3.0.

**Comment by jcaraballo17** [comment]
Done. 
@SRGDamia1 I noticed that you were not an administrator anymore. I didn't know if that was on purpose, so I gave you admin status again.

**Comment by aufdenkampe** [comment]
Awesome! Thanks.

**Comment by horsburgh** [comment]
I believe that this one is done. @jcaraballo17 - is this something that can be closed now, or does something need to be done on the production server? If you've given @aufdenkampe the right access already, go ahead and close this issue.

**Comment by aufdenkampe** [comment]
How can I tell that I'm a super user? I can't find any difference with the current "LimnoTech" user on sandbox.

Other than 'Allow super-users to add new variables and sensors' #71, what are the other capabilities of a super user?

**Comment by aufdenkampe** [comment]
Ah, I now see #50 describes the additional features:
* Jeff: "You would be able to see and edit any existing site registrations in the system. You could also register sites for other people. Our plan is that if an administrator is registering a site, they would get drop down of users (including themselves) where they would select the user for which they are registering the site."
* Juan: "When you're an administrator, the Register Site form has a new field called Deployed By in which you choose for whom you're registering the site. Also, when you go on a site detail page, the Edit and Delete buttons are available to you."

Unfortunately, I don't see those extra buttons that Juan mentioned.

**Comment by fryarludwig** [comment]
Are you still not seeing the extra options as a super user?

**Comment by aufdenkampe** [comment]
@fryarludwig, I just confirmed that the super user buttons do indeed work for me!

Speaking of which, @jcaraballo17, do you mind if I delete a few of your dummy sites, such as http://data.envirodiy.org/sites/qwerqwer/?

**Comment by aufdenkampe** [comment]
I just tried to delete that site, and it didn't seem to work.

**Comment by fryarludwig** [comment]
I've assigned both of those points to new issues, #117 and #118 so we can better track them. With those new issues, can we close this one again?

**Comment by aufdenkampe** [comment]
Yes! Thanks for your quick response @jcaraballo17!
