### ISSUE TITLE
Reduce the number of TCP handshakes and take other measures to reduce data usage

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#76]
- Make the response to the http post request as short as possible, preferably nothing more than the http response code (hopefully 201).
- Look into reducing other tcp overhead if possible.

See https://github.com/EnviroDIY/ModularSensors/issues/65

**Comment by horsburgh** [comment]
We can look into this, but given that TCP is a standard communication protocol, I'm not sure we want to fiddle with it. Making the response to the HTTP POST request shorter may be an option, but it is specific to whether there are settings in the web server to do this as it is the web server (and not our code) that forms these responses.

**Comment by SRGDamia1** [comment]
I think using CoAP on UDP might be a better option than switching to non-standard TCP.
