### ISSUE TITLE
Create examples of web service requests

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#8]
Need to post examples of web service POST requests for sending data to the data.envirodiy.org website with different encodings in the documentation for the website:

URL encoding
JSON encoding
...

**Comment by jcaraballo17** [comment]
Here are examples of the same post request with different content types.


**POST Request with urlencoded body**

```
POST //api/data-stream/ HTTP/1.1
Host: data.envirodiy.org
TOKEN: 0cd0616f-cf03-4789-aa28-82bca1b847f1

sampling_feature=f319af6a-3091-4070-b3ad-a606a7fdbed4&timestamp=2017-02-02 12:29:00&f8fbf90e-f59d-4736-af66-91fbee455433=8&52e6d5ce-eca1-4545-9b01-607a487cbfc0=10
```


**POST Request with json body**

```
POST //api/data-stream/ HTTP/1.1
Host: data.envirodiy.org
TOKEN: 0cd0616f-cf03-4789-aa28-82bca1b847f1
Content-Type: application/json

{
	"sampling_feature": "f319af6a-3091-4070-b3ad-a606a7fdbed4",
	"timestamp": "2017-02-02 12:29:00",
	"f8fbf90e-f59d-4736-af66-91fbee455433": 8,
	"52e6d5ce-eca1-4545-9b01-607a487cbfc0": 10
}

```

**Comment by horsburgh** [comment]
Added this to the milestone for Release 0.1.0, but really these examples just need to be moved to documentation and then I will close this issue.  I'll take care of that.

**Comment by horsburgh** [comment]
Added these to the documentation for this site. Closing.

**Comment by dancrocker** [comment]
It would be great if there was documentation for output structures as well. I am interested in scheduling automatic downloads of data from Monitor My Watershed (using an R script). I could not find instructions for how to do this elsewhere. Thanks!

**Comment by SRGDamia1** [comment]
@dancrocker - downloading the data is a completely different beast from the single-time-point POST requests.  I'm not sure we've ever really publicized any way to do that kind of scripted download.  @aufdenkampe could confirm, but the only way I'm coming up with that you could access the data in an web-service fashion is via the WoFpy endpoint:  http://data.wikiwatershed.org/wofpy/
