### ISSUE TITLE
Get sparklines to work in Safari

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2WebSDL#80]
I just noticed that when I open a site (such as http://data.envirodiy.org/sites/6/​) in Safari, the sparkline plot say "No data in the last 72 hours." 

Firefox and Chrome seem to work fine.

**Comment by aufdenkampe** [comment]
@Maurier, this is done, right?

**Comment by Maurier** [comment]
This has been fixed somehow. I'm not what caused it before, but I cannot reproduce it anymore.

**Comment by aufdenkampe** [comment]
Awesome! I also can't reproduce the error, so it's good for me!
