### ISSUE TITLE
Ordering of variables in list/code changes when site is changed

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#89]
When adding or removing a sensor from a site, the order of the other variables in the code snippet changes.  This makes it a pain to keep the code snippet aligned with the code that matches the values with the UUIDs.  The order should always be the same; new items should always be added at the end and removed ones taken out and everything else simply shifted up.

**Comment by SRGDamia1** [comment]
Also, the order of the plots should exactly match the order when you enter the "edit site" pane and should exactly match the order of the "code snippet."

**Comment by fryarludwig** [comment]
I've set the sites to order the variables by their sorting in the database. This may change some of your variable sortings in the sites once this is deployed, but won't change after that.

**Comment by SRGDamia1** [comment]
Was this change made on production or staging?  Anyway, the order seems not to be changing for me now.

**Comment by fryarludwig** [comment]
This hasn't yet made it to production or staging - the ordering won't be guaranteed until the next production release.

**Comment by aufdenkampe** [comment]
How do we test this?

**Comment by aufdenkampe** [comment]
No, we don't want to remove the code snippet. 
I've been meaning to comment on issue #139, to explain the recent substantial improvements to our https://github.com/EnviroDIY/ModularSensors repo., which has implications for the code snippet, which would ideally change to match the new expected syntax of [ModularSensors](https://github.com/EnviroDIY/ModularSensors). How we prioritize these changes is another matter, which we don't need to address now.

My comment was really to better understand what the tag "ready for testing" meant in this case.
If additional development work is actually needed, it is not worth prioritizing for this release, as we'll be revisiting the code snippet in the future.

**Comment by SRGDamia1** [comment]
The way I've re-structured the modular sensors library the UUID of a variable is directly tied to that variable in the variable constructor, instead of having two arrays (one of UUID's and one of variables) that must be matched order-wise.

This means that the order in the code snippet *DOES NOT* matter.  This issue can be closed.

As the constructor where the variable UUID belongs in the code also contains things like custom sensor names and variable labels, it would be essentially impossible to automatically generate a usable code snippet.  Thus providing any code snipped is unhelpful and misleading and the code snippet should be removed (#139).

The only caveat to removing the code snippet is that at this time the code snippet is the ONLY way to view any of the GUID's.  Therefor it cannot be removed until #92 and #163 are implemented.
