### ISSUE TITLE
Time Zone Support

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2WebSDL#9]
Need to make sure datetimes sent to the web service have time zone or UTCOffset information and are handled correctly in the database.

**Comment by SRGDamia1** [comment]
Please include the timezone as one of the defined variables spit out along with the GUIDs/tokens.

**Comment by horsburgh** [comment]
@SRGDamia1 - we plan to make the timezone information part of the date/time string using an ISO standard date format. This will be more compact than having a separate element split out.

**Comment by SRGDamia1** [comment]
I think that should be find for sending and receiving the data.  But the Mayfly itself doesn't support timezones, though, so the timezone value needs to be hard-coded into the program somewhere.  So I just wanted you to include the timezone value as one of the definitions in the "configuration code block" you're creating with the GUID's.

**Comment by horsburgh** [comment]
@SRGDamia1 - I added the time zone/UTCOffset information to what will be output as part of #9.

**Comment by horsburgh** [comment]
To support time zones in the date/time strings passed to the server, we will be using ISO 8601 date/time strings that can handle fractional seconds and offsets from UTC. Simple details are here:

https://www.w3.org/TR/NOTE-datetime

An example ISO 8601 compliant date/time string:

1997-07-16T19:20:30.45+01:00

**Comment by SRGDamia1** [comment]
Ok.  When will you be implementing this?

**Comment by horsburgh** [comment]
I just talked to @jcaraballo17 about this, so I think he's working on it now. I will let him fill you in.

**Comment by aufdenkampe** [comment]
@horsburgh, I like the ISO format. Although the DS3231 Real Time Clock (RTC) on the Mayfly doesn't support timezone natively, I like your solution to add it to outputted Arduino code declaration block that we are working on in issue #7. 

Unfortunately, the DS3231 RTC only provides whole second resolution. It would be great if we could have the option to send the date/time string without the decimal second.

**Comment by horsburgh** [comment]
@aufdenkampe - you can send the time without the fractional second. No problem.

**Comment by jcaraballo17** [comment]
Done! To ensure the integrity of the date, the web service will throw an exception when the timezone information is not in the timestamp.

Here are some examples of timestamps that the web service will accept:
"2017-02-07T16:13:00.45-07:00" 
"2017-02-07T16:13:00.45-0700" (offset without the ":" )
"2017-02-07T16:13:00-07:00" (time without fractional second)
"2017-02-07T16:13-07:00"  (time without seconds)

**Comment by SRGDamia1** [comment]
@jcaraballo17, Has this already gone up to production? The code I had working yesterday to send data stopped working.

**Comment by SRGDamia1** [comment]
Oh, I see it now is.

**Comment by SRGDamia1** [comment]
I've updated the example code I made to print the timestamp with the timezone.  Formatting text on the Arduino is a pain..

**Comment by horsburgh** [comment]
@SRGDamia1 - if you modified your code and have tested with the server and it is working OK, can you close this issue if you are satisfied?

@jcaraballo17 - We've taken care of this on the incoming end, but how do we show the UTCOffset information on the website?  We probably shouldn't close this until it's been handled in both places.

**Comment by horsburgh** [comment]
@SRGDamia1 - I see that you added the front end display of time zone information to issue #17, so you can close this as soon as you are satisfied that it is working to accept your data via the service.

**Comment by SRGDamia1** [comment]
My code is working and sending the data with the time zone and you seem to be receiving it just find.  Closing.
