### ISSUE TITLE
When attempting to view data via click from data.enviroDIY to webTSA, too many time series selected

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#98]
This bogs the system down and the graphics don't display

![clickhere](https://user-images.githubusercontent.com/5374350/33560685-71316a8e-d8de-11e7-8b58-6ca8ee3ae7d0.JPG)

![toomanydatasets](https://user-images.githubusercontent.com/5374350/33560689-740fd7b8-d8de-11e7-8914-8d7543830c94.JPG)

**Comment by fryarludwig** [comment]
This has been fixed
